const Table = ({ text }) => {
  return (
    <div className="list-table">
      <table>
        <thead>
          <th>Date</th>
          <th>From</th>
          <th>To</th>
          <th>Purpose</th>
          <th>Amount</th>
          <th>Verified</th>
        </thead>
        <tbody>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
          <tr>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
            <td>{text}</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};
export default Table;
